export default {
  "4-6 years old": [
    {"main": "Teddy Bear", "extra": ["soft", "hug", "bedtime"]},
    {"main": "Rainbow", "extra": ["sky", "colors", "rain"]},
    {"main": "Puppy", "extra": ["bark", "tail", "ball"]},
    {"main": "Ice Cream", "extra": ["cold", "sweet", "cone"]},
    {"main": "Bicycle", "extra": ["pedal", "bell", "wheels"]},
    {"main": "Kitten", "extra": ["meow", "milk", "whiskers"]},
    {"main": "Playground Swing", "extra": ["high", "push", "fly"]},
    {"main": "Muddy Puddle", "extra": ["splash", "boots", "jump"]},
    {"main": "Sweet Mango", "extra": ["juicy", "yellow", "slice"]},
    {"main": "Red Balloon", "extra": ["string", "air", "float"]},
    {"main": "Goldfish", "extra": ["bubbles", "water", "bowl"]},
    {"main": "Crayon Box", "extra": ["draw", "paper", "color"]},
    {"main": "Blanket Fort", "extra": ["pillow", "cozy", "secret"]},
    {"main": "Birthday Cake", "extra": ["candle", "slice", "frosting"]},
    {"main": "Fluffy Sheep", "extra": ["wool", "meadow", "grass"]},
    {"main": "Soap Bubbles", "extra": ["wand", "float", "pop"]},
    {"main": "School Backpack", "extra": ["zipper", "pocket", "books"]},
    {"main": "Crispy Dosa", "extra": ["plate", "chutney", "hot"]},
    {"main": "Toy Car", "extra": ["vroom", "road", "track"]},
    {"main": "Seashell", "extra": ["beach", "sand", "wave"]},
    {"main": "Garden Butterfly", "extra": ["flutter", "flower", "wings"]},
    {"main": "Apple Slice", "extra": ["crunch", "sweet", "fruit"]},
    {"main": "Yellow Sun", "extra": ["bright", "warm", "sky"]},
    {"main": "Bedtime Pillow", "extra": ["sleep", "soft", "dreams"]},
    {"main": "Baby Bunny", "extra": ["hop", "ears", "carrot"]},
    {"main": "Jumping Frog", "extra": ["lilypad", "green", "splash"]},
    {"main": "Picnic Basket", "extra": ["snacks", "blanket", "park"]},
    {"main": "Cardboard Box", "extra": ["tunnel", "hide", "tape"]},
    {"main": "Park Slide", "extra": ["ladder", "climb", "fast"]},
    {"main": "Rain Umbrella", "extra": ["handle", "drops", "open"]}
  ],
  "7-9 years old": [
    {"main": "Treehouse", "extra": ["ladder", "secret", "branches"]},
    {"main": "Magic Wand", "extra": ["sparkle", "spell", "glow"]},
    {"main": "Spaceship", "extra": ["rocket", "stars", "blastoff"]},
    {"main": "Dinosaur Fossil", "extra": ["bones", "dig", "museum"]},
    {"main": "Lunchbox Swap", "extra": ["tiffin", "paratha", "snack"]},
    {"main": "Water Gun", "extra": ["splash", "target", "soak"]},
    {"main": "School Bus", "extra": ["window", "horn", "conductor"]},
    {"main": "Telescope", "extra": ["planet", "crater", "lens"]},
    {"main": "Treasure Chest", "extra": ["gold", "lock", "hidden"]},
    {"main": "Skateboard", "extra": ["helmet", "balance", "wheels"]},
    {"main": "Secret Diary", "extra": ["key", "lock", "doodle"]},
    {"main": "Paper Airplane", "extra": ["fold", "glide", "distance"]},
    {"main": "Giant Slingshot", "extra": ["elastic", "launch", "aim"]},
    {"main": "Campfire", "extra": ["sparks", "marshmallow", "night"]},
    {"main": "Robotic Arm", "extra": ["gears", "metal", "remote"]},
    {"main": "Cricket Bat", "extra": ["sixer", "grip", "boundary"]},
    {"main": "Jungle Rope", "extra": ["swing", "canopy", "vine"]},
    {"main": "Underwater Goggles", "extra": ["swim", "corals", "dive"]},
    {"main": "Bumper Car", "extra": ["steering", "bump", "arcade"]},
    {"main": "Magnifying Glass", "extra": ["focus", "detective", "bugs"]},
    {"main": "Flying Carpet", "extra": ["clouds", "wind", "soar"]},
    {"main": "Remote Control", "extra": ["buttons", "channel", "batteries"]},
    {"main": "School Bell", "extra": ["recess", "ring", "corridor"]},
    {"main": "Pencil Sharpener", "extra": ["shavings", "blade", "point"]},
    {"main": "Return Gift", "extra": ["ribbon", "unboxing", "surprise"]},
    {"main": "Roller Skates", "extra": ["rink", "balance", "glide"]},
    {"main": "Lego Castle", "extra": ["bricks", "tower", "gate"]},
    {"main": "Water Balloon", "extra": ["splash", "sneak", "burst"]},
    {"main": "Comic Book", "extra": ["villain", "speech-bubble", "pages"]},
    {"main": "Haunted Attic", "extra": ["cobwebs", "chest", "shadow"]}
  ],
  "10-12 years old": [
    {"main": "Time Machine", "extra": ["portal", "future", "dial"]},
    {"main": "Submarine", "extra": ["periscope", "depths", "sonar"]},
    {"main": "Rollercoaster", "extra": ["loop", "screams", "steep"]},
    {"main": "Spicy Chaat", "extra": ["tamarind", "crunch", "street-stall"]},
    {"main": "Pocket Money", "extra": ["allowance", "savings", "piggy-bank"]},
    {"main": "Abandoned Shipwreck", "extra": ["barnacles", "diver", "cargo"]},
    {"main": "Solar Panel", "extra": ["sunlight", "grid", "clean-energy"]},
    {"main": "Midnight Feast", "extra": ["whisper", "snack", "pantry"]},
    {"main": "Virtual Pet", "extra": ["pixels", "feed", "screen"]},
    {"main": "Survival Knife", "extra": ["wilderness", "rope", "carve"]},
    {"main": "Stage Microphone", "extra": ["spotlight", "applause", "rehearsal"]},
    {"main": "Dormitory Bunk", "extra": ["ladder", "top-berth", "pillow"]},
    {"main": "Board Exam", "extra": ["timer", "answer-sheet", "revision"]},
    {"main": "Volcano Crater", "extra": ["magma", "smoke", "eruption"]},
    {"main": "Street Momo", "extra": ["steamer", "chutney", "filling"]},
    {"main": "Electric Scooter", "extra": ["throttle", "commute", "battery"]},
    {"main": "Hidden Trapdoor", "extra": ["hinges", "basement", "lantern"]},
    {"main": "Drone Camera", "extra": ["propellers", "aerial", "remote"]},
    {"main": "Compass Dial", "extra": ["needle", "cardinal", "trail"]},
    {"main": "Sports Trophy", "extra": ["podium", "engraving", "championship"]},
    {"main": "Escape Room", "extra": ["riddle", "code", "countdown"]},
    {"main": "Camp Tent", "extra": ["stakes", "zipper", "forest"]},
    {"main": "Astronaut Helmet", "extra": ["visor", "oxygen", "zero-gravity"]},
    {"main": "Railway Berth", "extra": ["chai", "tracks", "scenery"]},
    {"main": "Secret Compartment", "extra": ["false-bottom", "latch", "keepsake"]},
    {"main": "Stopwatch", "extra": ["split-second", "lap", "sprint"]},
    {"main": "Glow Stick", "extra": ["snap", "neon", "darkness"]},
    {"main": "Power Cut", "extra": ["inverter", "candlelight", "terrace"]},
    {"main": "Binoculars", "extra": ["wildlife", "safari", "distant"]},
    {"main": "Maglev Train", "extra": ["magnets", "high-speed", "rails"]}
  ],
  "13-15 years old": [
    {"main": "Smartphone Addiction", "extra": ["notifications", "screen-time", "dopamine"]},
    {"main": "Virtual Reality", "extra": ["headset", "immersion", "simulation"]},
    {"main": "Artificial Intelligence", "extra": ["neural-net", "automation", "creativity"]},
    {"main": "Street Food", "extra": ["hygiene", "spices", "vendors"]},
    {"main": "Fast Fashion", "extra": ["micro-trends", "landfill", "haul"]},
    {"main": "School Uniform", "extra": ["conformity", "identity", "equality"]},
    {"main": "Social Validation", "extra": ["likes", "follower-count", "algorithm"]},
    {"main": "Electric Vehicle", "extra": ["range", "sustainability", "battery"]},
    {"main": "Group Project", "extra": ["freeloader", "deadline", "slideshow"]},
    {"main": "Cancel Culture", "extra": ["boycott", "backlash", "accountability"]},
    {"main": "Boarding School", "extra": ["curfew", "independence", "roommate"]},
    {"main": "Cybersecurity", "extra": ["firewall", "encryption", "breach"]},
    {"main": "Energy Drink", "extra": ["caffeine", "crash", "performance"]},
    {"main": "Food Delivery App", "extra": ["gig-worker", "courier", "convenience"]},
    {"main": "E-Sports", "extra": ["tournament", "reflexes", "streaming"]},
    {"main": "Pocket Diary", "extra": ["mindfulness", "habits", "reflection"]},
    {"main": "Peer Pressure", "extra": ["belonging", "choices", "boundaries"]},
    {"main": "Solo Travel", "extra": ["itinerary", "hostel", "self-discovery"]},
    {"main": "Sneaker Reselling", "extra": ["hypebeast", "markup", "limited-drop"]},
    {"main": "Digital Footprint", "extra": ["privacy", "archive", "permanent"]},
    {"main": "Parental Curfew", "extra": ["negotiation", "trust", "liberty"]},
    {"main": "Space Tourism", "extra": ["commercial-flight", "orbit", "billionaire"]},
    {"main": "Printed Paperback", "extra": ["bookmarks", "nostalgia", "screen-free"]},
    {"main": "Sleep Deprivation", "extra": ["late-night", "alarm", "fatigue"]},
    {"main": "Noise-Canceling Headphones", "extra": ["isolation", "focus", "commute"]},
    {"main": "Plastic Pollution", "extra": ["single-use", "oceans", "microplastics"]},
    {"main": "Music Festival", "extra": ["crowd", "stage", "soundtrack"]},
    {"main": "Standardized Testing", "extra": ["rote-memory", "anxiety", "percentile"]},
    {"main": "Minimalist Lifestyle", "extra": ["clutter", "simplicity", "consumption"]},
    {"main": "Deepfake Video", "extra": ["manipulation", "identity", "ethics"]}
  ]
}
