export default {
  "4-6 years old": [
    {"main": "If My Teddy Bear Could Talk for One Day", "extra": ["whisper", "blanket", "cookie"]},
    {"main": "The Day I Splashed in the Biggest Muddy Puddle", "extra": ["boots", "frog", "splash"]},
    {"main": "My Favorite Ice Cream Flavor in the Whole World", "extra": ["sticky", "cherry", "melt"]},
    {"main": "If I Turned into a Chirpy Little Bird", "extra": ["wings", "treetop", "sing"]},
    {"main": "Why I Love Visiting My Grandparents' House", "extra": ["story", "hug", "treat"]},
    {"main": "The Magic Slide at the Playground", "extra": ["whoosh", "sand", "climb"]},
    {"main": "My Super Bright Box of Crayons", "extra": ["rainbow", "doodle", "yellow"]},
    {"main": "Dressing Up in My Best Festive Clothes", "extra": ["sparkle", "sweets", "shoes"]},
    {"main": "If My Pet Puppy Was the Teacher Today", "extra": ["bark", "tail", "recess"]},
    {"main": "The Prettiest Butterfly in the Garden", "extra": ["flutter", "flower", "sunshine"]},
    {"main": "Building a Giant Blanket Fort in the Living Room", "extra": ["pillow", "flashlight", "secret"]},
    {"main": "Why Mangoes Are the Best Fruit Ever", "extra": ["juicy", "slice", "sweet"]},
    {"main": "The Funniest Face I Can Make", "extra": ["mirror", "giggle", "tongue"]},
    {"main": "Pretending to Swim Like a Little Fish", "extra": ["bubbles", "water", "fin"]},
    {"main": "My Bedtime Story and the Cozy Pajamas", "extra": ["moon", "yawn", "star"]},
    {"main": "Blowing Huge Soap Bubbles in the Air", "extra": ["pop", "wind", "chase"]},
    {"main": "Going to School with My New Backpack", "extra": ["zipper", "bottle", "smile"]},
    {"main": "The Noisiest Toy Car I Own", "extra": ["vroom", "wheel", "race"]},
    {"main": "Bursting with Joy at a Birthday Party", "extra": ["balloon", "candle", "cake"]},
    {"main": "A Magic Red Apple That Gives Super Speed", "extra": ["crunch", "pocket", "fast"]},
    {"main": "Playing Hide-and-Seek Behind the Curtains", "extra": ["quiet", "feet", "found"]},
    {"main": "Feeding Green Leaves to a Friendly Goat", "extra": ["chew", "grass", "gentle"]},
    {"main": "Singing Nursery Rhymes on the Car Ride", "extra": ["window", "music", "clap"]},
    {"main": "My Big Rainy Day Umbrella", "extra": ["raindrop", "yellow", "twirl"]},
    {"main": "What I Do When I See a Rainbow", "extra": ["sky", "colors", "point"]},
    {"main": "Pretending to Be a Sleepy Kitten", "extra": ["meow", "milk", "nap"]},
    {"main": "Drawing a Purple Elephant with Crayons", "extra": ["paper", "ears", "silly"]},
    {"main": "Eating Crispy Dosas with Mom and Dad", "extra": ["plate", "crisp", "chutney"]},
    {"main": "A Sunny Day on the Swings", "extra": ["push", "higher", "laugh"]},
    {"main": "The Softest Blanket That Keeps Me Warm", "extra": ["cozy", "tuck", "dreams"]}
  ],
  "7-9 years old": [
    {"main": "The School Bus Seat Window Mystery", "extra": ["puddle", "horn", "conductor"]},
    {"main": "What If My Eraser Could Erase Real-Life Objects?", "extra": ["chalkboard", "accident", "disappear"]},
    {"main": "The Great Lunchbox Trade: Paratha for Noodles", "extra": ["spill", "tiffin", "napkin"]},
    {"main": "The Morning Sprint When the Alarm Didn't Ring", "extra": ["shoelace", "toothbrush", "toast"]},
    {"main": "Caught Soaked in a Sudden Downpour on the Way Home", "extra": ["drench", "paper-boat", "lightning"]},
    {"main": "Inventing a Machine That Cleans Up Legos Instantly", "extra": ["magnet", "gears", "clatter"]},
    {"main": "The Day Our Colony Cricket Ball Broke an Uncle's Plant Pot", "extra": ["sixer", "wicket", "apology"]},
    {"main": "Super Gadgets Hidden Inside My Pencil Box", "extra": ["laser", "ruler", "secret-button"]},
    {"main": "Grocery Trolley Races Down the Supermarket Aisle", "extra": ["snack", "wheels", "danger"]},
    {"main": "The Day I Lost My New Water Bottle at School", "extra": ["lost-and-found", "corridor", "sticker"]},
    {"main": "Learning to Ride a Bicycle Without Training Wheels", "extra": ["wobble", "bandage", "balance"]},
    {"main": "Fighting for the TV Remote During Cartoon Time", "extra": ["sofa", "channel", "pillow-shield"]},
    {"main": "Unwrapping the Best Birthday Return Gift Ever", "extra": ["ribbon", "glitter", "surprise"]},
    {"main": "The Funniest Classroom Moment When the Teacher Sneeze-Laughed", "extra": ["bench", "chuckle", "chalk"]},
    {"main": "Sneaking a Midnight Gulab Jamun from the Fridge", "extra": ["creak", "spoon", "syrup"]},
    {"main": "A Treehouse That Takes You to a Hidden Jungle", "extra": ["ladder", "monkey", "map"]},
    {"main": "If Dogs Could Talk and Attend Our School", "extra": ["homework", "leash", "recess"]},
    {"main": "The Magic Pen That Writes Answers Automatically", "extra": ["ink", "exam", "sparkle"]},
    {"main": "Catching Fireflies in Grandma's Backyard", "extra": ["jar", "glow", "crickets"]},
    {"main": "The Day the Classroom Ceiling Fan Blew All the Papers Away", "extra": ["cyclone", "flutter", "chase"]},
    {"main": "Trying Ice Skating for the Very First Time", "extra": ["slippery", "helmet", "thump"]},
    {"main": "What If Rain Tasted Like Mango Frooti?", "extra": ["gulps", "clouds", "straw"]},
    {"main": "The Colony Park Ghost Rumor That Turned Out to Be a Cat", "extra": ["flashlight", "bush", "shadow"]},
    {"main": "My Dad's Embarrassing Loud Sneeze in the Cinema Hall", "extra": ["popcorn", "echo", "silence"]},
    {"main": "If I Could Fly a Kite Higher Than the Clouds", "extra": ["string", "wind", "rooftop"]},
    {"main": "The Mystery of the Vanishing Single Socks", "extra": ["washing-machine", "drawer", "clue"]},
    {"main": "When Mom Swapped My Junk Food for Bitter Gourd", "extra": ["smell", "disguise", "negotiate"]},
    {"main": "Building the Ultimate Pillow Fortress to Defend Against Siblings", "extra": ["cushion", "ambush", "surrender"]},
    {"main": "If Video Game Characters Escaped into My Bedroom", "extra": ["pixel", "joystick", "portal"]},
    {"main": "The Stray Dog That Walks Me to the School Bus Everyday", "extra": ["biscuit", "tail-wag", "pavement"]}
  ],
  "10-12 years old": [
    {"main": "Last-Minute Exam Panic: Studying the Wrong Chapter", "extra": ["timetable", "highlighter", "blank"]},
    {"main": "The Ultimate Street Food Showdown: Golgappa vs. Momos", "extra": ["spicy", "vendor", "crunch"]},
    {"main": "A Sudden Power Cut on a Sweltering Summer Night", "extra": ["balcony", "candle", "sweat"]},
    {"main": "The Drama of Sibling Territory Wars Over the Bedroom Line", "extra": ["chalk-line", "boundary", "pillow-fight"]},
    {"main": "Waking Up at 5 AM on a Freezing Winter Morning", "extra": ["quilt", "shiver", "snooze"]},
    {"main": "If My Shoes Had Built-in Mini Rocket Boosters", "extra": ["blastoff", "laces", "rooftop"]},
    {"main": "The Chaos of Packing a Heavy School Bag to Beat the Bag Check", "extra": ["timetable", "zipper-jam", "shoulder-pain"]},
    {"main": "Finding Out the Annual Day Costume Is Absolutely Ridiculous", "extra": ["sequins", "backstage", "tail"]},
    {"main": "Saving Every Rupee of Pocket Money for That One Dream Item", "extra": ["piggy-bank", "temptation", "receipt"]},
    {"main": "The Day the Cricket Ball Vanished Inside an Abandoned House", "extra": ["over-the-wall", "creaky-gate", "cobwebs"]},
    {"main": "Train Journeys: Fighting for the Upper Berth", "extra": ["chai-seller", "suitcase", "window-seat"]},
    {"main": "Inventing an Automatic Excuse Generator for Late Homework", "extra": ["dog-ate-it", "glitch", "believable"]},
    {"main": "Surviving an Entire 24 Hours Without the Internet", "extra": ["boredom", "board-game", "reboot"]},
    {"main": "Helping Mom Cook Dinner and Accidentally Doubling the Salt", "extra": ["recipe", "tadka", "water-jug"]},
    {"main": "The Euphoria of the Final School Bell Before Summer Vacation", "extra": ["stampede", "cheer", "freedom"]},
    {"main": "If Humans Could Breathe Underwater and Explore Sunken Cities", "extra": ["gills", "coral", "treasure-chest"]},
    {"main": "The Worst Haircut of My Life Right Before School Photos", "extra": ["bangs", "mirror-shock", "comb-over"]},
    {"main": "What If History Books Only Recorded Funny Moments?", "extra": ["crown", "banana-peel", "duel"]},
    {"main": "Stranded in an Elevator with a Singing Stranger", "extra": ["emergency-button", "echo", "awkward"]},
    {"main": "Sports Day Relay Race: The Dropped Baton Disaster", "extra": ["ankle-twist", "whistle", "finish-line"]},
    {"main": "A Device That Tells You What Your Pet Thinks of You", "extra": ["collar", "translation", "attitude"]},
    {"main": "Sneaking Midnight Snacks During a Sleepover", "extra": ["creaky-floor", "whisper", "crisps"]},
    {"main": "If School Subjects Were People Having an Argument", "extra": ["math-formula", "grammar-police", "clash"]},
    {"main": "My First Time Getting Left Behind for Ten Minutes at the Mall", "extra": ["announcement", "security", "ice-cream-cone"]},
    {"main": "The Most Dangerous Game of Floor Is Lava Ever Played", "extra": ["cushion-island", "leap", "carpet-burn"]},
    {"main": "Accidentally Replying All on the School Class Group Chat", "extra": ["screenshot", "panic", "typing-dots"]},
    {"main": "Finding a 100-Year-Old Coin Under the Floorboards", "extra": ["tarnish", "magnifying-glass", "secret"]},
    {"main": "The Art of Bargaining at the Local Flea Market", "extra": ["discount", "poker-face", "deal"]},
    {"main": "Inventing a Backpack That Carries You Instead", "extra": ["straps", "engine", "autopilot"]},
    {"main": "When the School Science Project Spilled and Bubbled Everywhere", "extra": ["vinegar", "volcano", "mop"]}
  ],
  "13-15 years old": [
    {"main": "Should School Start at 10 AM to Match Teenage Sleep Cycles?", "extra": ["circadian-rhythm", "productivity", "exhaustion"]},
    {"main": "The Toxic Pressure of Maintaining Social Media Snap Streaks", "extra": ["validation", "notification", "burnout"]},
    {"main": "Street Food Stalls vs. Fast Food Mega Chains: The Culture Battle", "extra": ["authenticity", "franchise", "spice-levels"]},
    {"main": "Will Artificial Intelligence Make Human Homework Obsolete?", "extra": ["algorithm", "originality", "plagiarism"]},
    {"main": "The Social Hierarchy of Choosing Where to Sit in the Cafeteria", "extra": ["clique", "awkwardness", "bench"]},
    {"main": "If You Could Erase One Mundane Chore From Existence", "extra": ["ironing", "dishes", "monotony"]},
    {"main": "Surviving Long Family Weddings: Between Posing and Binge-Eating", "extra": ["outfit-itch", "relatives", "buffet"]},
    {"main": "The Reality Behind Influencer 'Day in the Life' Videos", "extra": ["aesthetic", "filter", "delusion"]},
    {"main": "Should Competitive Video Gaming Be Officially Included in the Olympics?", "extra": ["reflexes", "athlete", "spectacle"]},
    {"main": "The Dread of Group Projects Where One Person Does Everything", "extra": ["freeloader", "deadline", "slideshow"]},
    {"main": "Dealing with the Dreaded Parental 'Compare and Contrast' Lecture", "extra": ["topper", "neighbor", "lecture"]},
    {"main": "Is Streaming Making Us Forget How to Watch an Entire Movie?", "extra": ["attention-span", "binge", "rewind"]},
    {"main": "The Ethical Dilemma of Genetic Engineering in Pets", "extra": ["designer", "consequences", "species"]},
    {"main": "Why Nostalgia for Childhood Hits Harder in High School", "extra": ["playground", "innocence", "milestone"]},
    {"main": "Can True Friendships Survive Without Daily Online Chatting?", "extra": ["ghosting", "loyalty", "connection"]},
    {"main": "The Problem with School Dress Codes: Discipline or Restriction?", "extra": ["conformity", "identity", "guidelines"]},
    {"main": "The Craze of Sneaker Culture: Fashion Statement or Waste of Cash?", "extra": ["hypebeast", "resale", "comfort"]},
    {"main": "If High Schools Replaced Chemistry with Financial Literacy", "extra": ["taxes", "investment", "budgeting"]},
    {"main": "Solo Traveling at 18: Ultimate Freedom or Romanticized Trouble?", "extra": ["budget", "hostel", "independence"]},
    {"main": "The Psychological Warfare of Unread Blue Ticks and 'Seen' Receipts", "extra": ["overthinking", "anxiety", "airplane-mode"]},
    {"main": "Are AI Chatbots Good Companions or Dangerous Substitutes?", "extra": ["empathy", "isolation", "code"]},
    {"main": "Why Everyone Suddenly Claims to Have an Aesthetic Lifestyle", "extra": ["curated", "vibe", "superficial"]},
    {"main": "The Environmental Cost of 10-Minute Fast Delivery Apps", "extra": ["exhaustion", "packaging", "instant-gratification"]},
    {"main": "If Teenagers Ran the Country for Exactly One Week", "extra": ["cabinet", "curfew", "reform"]},
    {"main": "The Dying Habit of Reading Printed Books Over E-Readers", "extra": ["spine-crease", "paper-smell", "screen-glare"]},
    {"main": "Why Do Adults Forget What It Actually Feels Like to Be a Teen?", "extra": ["empathy-gap", "dismissive", "rebellion"]},
    {"main": "Cancel Culture: Holding People Accountable or Digital Mob Justice?", "extra": ["boycott", "redemption", "mob-mentality"]},
    {"main": "The True Cost of Fast Fashion Trends on Youth Wallets and the Planet", "extra": ["thrift", "landfill", "micro-trends"]},
    {"main": "Should Board Exam Scores Define a Student's Worth?", "extra": ["meritocracy", "memorization", "potential"]},
    {"main": "The Art of Mastering the 'French Exit' at Loud Social Gatherings", "extra": ["stealth", "goodbyes", "relief"]}
  ]
};